export const LIST_PRODUCT_CASUAL = [
  {
    image: '/product_1.png',
    name: 'Gradient Graphic T-shirt',
    star: 3.5,
    price: '$145',
    // cost: '$232',
    // sale: '-20%',
  },
  {
    image: '/product_1.png',
    name: 'Polo with Tipping Details',
    star: 4.5,
    price: '$180',
  },
  {
    image: '/product_1.png',
    name: 'Black Striped T-shirt',
    star: 5,
    price: '$120',
    cost: '$150',
    sale: '-30%',
  },
  {
    image: '/product_1.png',
    name: 'Skin Fit Jeans',
    star: 3.5,
    price: '$240',
    cost: '$260',
    sale: '-20%',
  },
  {
    image: '/product_1.png',
    name: 'Checkered Shirt',
    star: 4.5,
    price: '$180',
  },
  {
    image: '/product_1.png',
    name: 'Sleeve Striped T-shirt',
    star: 3.5,
    price: '$130',
    cost: '$160',
    sale: '-30%',
  },
  {
    image: '/product_1.png',
    name: 'Vertical Striped Shirt',
    star: 5,
    price: '$212',
    cost: '$232',
    sale: '-20%',
  },
  {
    image: '/product_1.png',
    name: 'Courage Graphic T-shirt',
    star: 4,
    price: '$145',
  },
  {
    image: '/product_1.png',
    name: 'Loose Fit Bermuda Shorts',
    star: 3,
    price: '$80',
  },
];
